#服务器配置
server:
  port: 80


spring:
  #数据源
  datasource:
    # 系统数据源
    system:
      url: jdbc:mysql://localhost:3306/system?serverTimezone=Asia/Shanghai&characterEncoding=utf8
      username: root
      password: 123456
      configuration:
        maximum-pool-size: 10

    # 业务数据源
    server:
      url: jdbc:mysql://localhost:3306/server?serverTimezone=Asia/Shanghai&characterEncoding=utf8
      username: root
      password: 123456
      configuration:
        maximum-pool-size: 10

# 日志
logging:
  level:
    com.springboot.ssm.mapper: debug # 显示执行sql
