spring:
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/ssm?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456

mybatis-plus:
  mapperLocations: classpath*:mapper/*.xml
  #起别名。可省略写mybatis的xml中的resultType的全路径
  typeAliasesPackage: com.springboot.ssm.domain

# 日志
logging:
  level:
    com.springboot.ssm.mapper: debug # 显示执行sql
